#配置随机值，RandomValuePropertySource注入随机值
spring:
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://121.42.44.189:3306/test
  username: root
  password: 123456
 jpa:
  hibernate.ddl-auto: update
#  show-sql: true
  database: MYSQL
  mvc:
   view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp


logging:
#  config: ./logback.xml


